# Generated by Django 3.2.14 on 2023-09-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='Course_Duration_In_Months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='Fee_Installments',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='Total_Fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
