# Generated by Django 3.2.14 on 2023-09-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='reason',
            field=models.CharField(blank=True, choices=[('Admission Fee', 'Admission Fee'), ('Monthly Fee', 'Monthly Fee'), ('Other', 'Other')], max_length=30, null=True),
        ),
    ]
